"""Tests for FormGenerator — 7-page planning application PDF generator.

# DESIGN: Tests are written first (TDD) and cover the public contract of
# FormGenerator.  They do not inspect internal layout details — only the
# observable outputs: PDF validity, page count, placed-value coverage, pixel
# coordinate sanity, and seed determinism.  This keeps the tests stable even
# if the visual layout evolves.
"""

from __future__ import annotations

import pytest

from planproof.datagen.rendering.form_generator import FormGenerator
from planproof.datagen.rendering.models import PlacedValue
from planproof.datagen.scenario.models import DocumentSpec, Scenario, Value, Verdict


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------

def _make_scenario(seed: int = 42) -> Scenario:
    """Build a minimal but realistic Scenario for form generation tests.

    # WHY: Constructing the full Scenario here (rather than mocking it) keeps
    # the tests honest — the generator must handle real Value objects, not just
    # dict look-alikes.  The values mirror a typical householder application so
    # the tests exercise the main code paths without unnecessary complexity.
    """
    values = (
        Value(
            attribute="building_height",
            value=7.5,
            unit="metres",
            display_text="7.5m",
        ),
        Value(
            attribute="site_coverage",
            value=35.0,
            unit="percent",
            display_text="35%",
        ),
    )
    doc_spec = DocumentSpec(
        doc_type="FORM",
        file_format="pdf",
        values_to_place=("building_height", "site_coverage"),
    )
    return Scenario(
        set_id="SET_TEST001",
        category="compliant",
        seed=seed,
        profile_id="householder",
        difficulty="low",
        degradation_preset="none",
        values=values,
        verdicts=(
            Verdict(
                rule_id="R001",
                outcome="PASS",
                evaluated_value=7.5,
                threshold=8.0,
            ),
        ),
        documents=(doc_spec,),
        edge_case_strategy=None,
    )


def _make_doc_spec() -> DocumentSpec:
    return DocumentSpec(
        doc_type="FORM",
        file_format="pdf",
        values_to_place=("building_height", "site_coverage"),
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestFormGeneratorPdfValidity:
    """FormGenerator must produce valid PDF bytes."""

    def test_generates_pdf(self) -> None:
        """content_bytes must start with the PDF magic bytes %PDF.

        # WHY: If reportlab fails silently or returns an empty buffer, this
        # test is the first line of defence — it catches serialisation errors
        # before any more expensive checks run.
        """
        generator = FormGenerator()
        scenario = _make_scenario()
        doc_spec = _make_doc_spec()

        result = generator.generate(scenario, doc_spec, seed=42)

        assert result.content_bytes[:4] == b"%PDF", (
            "Generated bytes do not start with PDF magic header"
        )

    def test_content_bytes_nonempty(self) -> None:
        """PDF content must be a non-trivially-sized byte string.

        # WHY: An empty or near-empty PDF would pass the magic-bytes check but
        # clearly indicates a serialisation failure.  1 KB is a safe lower bound
        # for a 7-page document with text content.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        assert len(result.content_bytes) > 1024, (
            f"PDF is suspiciously small: {len(result.content_bytes)} bytes"
        )


class TestFormGeneratorPageCount:
    """FormGenerator must produce exactly 7 pages."""

    def test_correct_page_count(self) -> None:
        """The generated PDF must contain exactly 7 pages.

        # WHY: The form structure (application header → declaration) is a
        # fixed-length 7-page document modelled after real BCC householder
        # applications.  Deviating from this count indicates a structural
        # regression in the page-building logic.
        """
        # WHY: We import PyMuPDF only in this test so the main package does
        # not require it as a hard dependency — it lives in the optional `pdf`
        # extra.  If fitz is not installed this test is skipped gracefully.
        fitz = pytest.importorskip("fitz", reason="pymupdf not installed")

        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        doc = fitz.open(stream=result.content_bytes, filetype="pdf")
        try:
            assert doc.page_count == 7, (
                f"Expected 7 pages, got {doc.page_count}"
            )
        finally:
            doc.close()


class TestFormGeneratorPlacedValues:
    """FormGenerator must record a PlacedValue for every value in values_to_place."""

    def test_placed_values_tracked(self) -> None:
        """At least one PlacedValue must be recorded per requested value.

        # WHY: The primary contract of the generator is to embed ground-truth
        # values and return their locations.  If a value listed in
        # doc_spec.values_to_place has no corresponding PlacedValue, the
        # evaluation harness will have missing ground-truth labels for that
        # attribute — silently degrading dataset quality.
        """
        generator = FormGenerator()
        scenario = _make_scenario()
        doc_spec = _make_doc_spec()

        result = generator.generate(scenario, doc_spec, seed=42)

        placed_attributes = {pv.attribute for pv in result.placed_values}
        for attr in doc_spec.values_to_place:
            assert attr in placed_attributes, (
                f"No PlacedValue recorded for attribute '{attr}'"
            )

    def test_placed_values_is_tuple(self) -> None:
        """placed_values must be a tuple for deep immutability of GeneratedDocument.

        # WHY: GeneratedDocument is a frozen dataclass; storing placed_values
        # as a list would allow downstream mutation of the ground-truth corpus.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        assert isinstance(result.placed_values, tuple), (
            f"placed_values should be tuple, got {type(result.placed_values)}"
        )

    def test_site_address_tracked(self) -> None:
        """A site_address PlacedValue must always be present, even without a
        corresponding Value in doc_spec.values_to_place.

        # WHY: The site address appears on the form for every planning
        # application.  Generating and tracking it ensures the evaluation
        # harness can verify address extraction even when the scenario does
        # not include a site_address compliance rule.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        placed_attributes = {pv.attribute for pv in result.placed_values}
        assert "site_address" in placed_attributes, (
            "site_address must always be tracked as a PlacedValue"
        )


class TestFormGeneratorBoundingBoxes:
    """All bounding boxes must be valid pixel coordinates at 300 DPI."""

    def test_bounding_boxes_in_pixel_coords(self) -> None:
        """x,y must be >= 0 and width,height must be > 0 for every PlacedValue.

        # WHY: Negative coordinates or zero-size boxes indicate coordinate
        # conversion errors (e.g. applying the PDF Y-flip incorrectly).  These
        # would cause the evaluation harness to crop invalid regions and report
        # false extraction failures.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        for pv in result.placed_values:
            bb = pv.bounding_box
            assert bb.x >= 0, f"{pv.attribute}: bounding_box.x={bb.x} is negative"
            assert bb.y >= 0, f"{pv.attribute}: bounding_box.y={bb.y} is negative"
            assert bb.width > 0, f"{pv.attribute}: bounding_box.width={bb.width} <= 0"
            assert bb.height > 0, (
                f"{pv.attribute}: bounding_box.height={bb.height} <= 0"
            )

    def test_bounding_boxes_have_valid_page(self) -> None:
        """page must be >= 1 (1-based index) for every PlacedValue.

        # WHY: A page of 0 would mean the renderer tried to place a value on a
        # non-existent page, indicating an off-by-one error in the page index.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        for pv in result.placed_values:
            assert pv.bounding_box.page >= 1, (
                f"{pv.attribute}: bounding_box.page={pv.bounding_box.page} < 1"
            )
            assert pv.page >= 1, (
                f"{pv.attribute}: placed_value.page={pv.page} < 1"
            )

    def test_bounding_boxes_within_a4_page(self) -> None:
        """Bounding boxes must lie within the A4 page dimensions at 300 DPI.

        # WHY: A4 at 300 DPI is 2480 x 3508 pixels.  Any bounding box outside
        # this area indicates a coordinate conversion bug where the value was
        # placed outside the physical page boundaries — those crops would be
        # blank in any downstream OCR pipeline.
        """
        # A4 at 300 DPI: 210mm × 297mm = 2480 × 3508 pixels (rounded up).
        A4_WIDTH_PX = 2481   # slight tolerance for floating-point rounding
        A4_HEIGHT_PX = 3509

        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        for pv in result.placed_values:
            bb = pv.bounding_box
            assert bb.x + bb.width <= A4_WIDTH_PX, (
                f"{pv.attribute}: box right edge {bb.x + bb.width:.1f} "
                f"exceeds A4 width {A4_WIDTH_PX}px"
            )
            assert bb.y + bb.height <= A4_HEIGHT_PX, (
                f"{pv.attribute}: box bottom edge {bb.y + bb.height:.1f} "
                f"exceeds A4 height {A4_HEIGHT_PX}px"
            )


class TestFormGeneratorDeterminism:
    """Same seed must produce identical output every time."""

    def test_seed_determinism(self) -> None:
        """Two generate() calls with the same seed must produce identical placed_values.

        # WHY: Determinism is the foundation of reproducible dataset generation.
        # If positions differ between runs with the same seed, the ground-truth
        # corpus is non-reproducible and the evaluation harness cannot verify
        # that regenerated documents match stored labels.
        """
        generator = FormGenerator()
        scenario = _make_scenario(seed=99)
        doc_spec = _make_doc_spec()

        result_a = generator.generate(scenario, doc_spec, seed=99)
        result_b = generator.generate(scenario, doc_spec, seed=99)

        assert result_a.placed_values == result_b.placed_values, (
            "Two generate() calls with seed=99 produced different placed_values"
        )

    def test_different_seeds_differ(self) -> None:
        """Different seeds should (very likely) produce different random content.

        # WHY: If all seeds produce identical output, the seed parameter is
        # not wired correctly — the determinism guarantee would be vacuously
        # true but useless for varied corpus generation.

        # DESIGN: We compare content_bytes rather than placed_values because
        # the random content (applicant names, descriptions) lives in the PDF
        # bytes even when the value positions happen to be the same.
        """
        generator = FormGenerator()
        doc_spec = _make_doc_spec()

        result_a = generator.generate(_make_scenario(seed=1), doc_spec, seed=1)
        result_b = generator.generate(_make_scenario(seed=2), doc_spec, seed=2)

        assert result_a.content_bytes != result_b.content_bytes, (
            "Seeds 1 and 2 produced identical PDF bytes — seed is not wired"
        )


class TestFormGeneratorMetadata:
    """GeneratedDocument metadata must be correct."""

    def test_doc_type_is_form(self) -> None:
        """doc_type must be DocumentType.FORM."""
        from planproof.schemas.entities import DocumentType

        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        assert result.doc_type == DocumentType.FORM

    def test_file_format_is_pdf(self) -> None:
        """file_format must be 'pdf'."""
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        assert result.file_format == "pdf"

    def test_filename_contains_set_id(self) -> None:
        """Filename must incorporate the scenario set_id for traceability.

        # WHY: Including the set_id in the filename ensures that outputs stored
        # to disk can always be traced back to their generating scenario without
        # reading the file contents.
        """
        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        assert "SET_TEST001" in result.filename, (
            f"set_id 'SET_TEST001' not in filename '{result.filename}'"
        )

    def test_entity_types_correct(self) -> None:
        """Numeric values must use MEASUREMENT entity type; address uses ADDRESS.

        # WHY: EntityType drives extraction routing downstream.  A mis-labelled
        # MEASUREMENT would be routed to the address extractor (and vice versa),
        # causing silent extraction failures that are hard to diagnose.
        """
        from planproof.schemas.entities import EntityType

        generator = FormGenerator()
        result = generator.generate(_make_scenario(), _make_doc_spec(), seed=42)

        for pv in result.placed_values:
            if pv.attribute == "site_address":
                assert pv.entity_type == EntityType.ADDRESS, (
                    f"site_address should be ADDRESS, got {pv.entity_type}"
                )
            else:
                assert pv.entity_type == EntityType.MEASUREMENT, (
                    f"Numeric attribute '{pv.attribute}' should be MEASUREMENT, "
                    f"got {pv.entity_type}"
                )

    def test_protocol_conformance(self) -> None:
        """FormGenerator must satisfy the DocumentGenerator Protocol.

        # WHY: Protocol conformance is checked at import time by mypy, but
        # runtime_checkable lets us add an explicit isinstance assertion here
        # to catch cases where a method was renamed or removed.
        """
        from planproof.datagen.rendering.registry import DocumentGenerator

        generator = FormGenerator()
        assert isinstance(generator, DocumentGenerator), (
            "FormGenerator does not satisfy the DocumentGenerator Protocol"
        )
