"""Coverage tests — skip if full dataset not generated.

# DESIGN: These tests are designed to run against the full synthetic corpus
# (data/synthetic/) generated by running the data-gen pipeline at full scale.
# They are *skipped* in CI when the corpus has not been generated, because
# generating 50 sets takes ~minutes and is not suitable for a fast feedback
# loop.
#
# WHY a separate file from test_datagen_pipeline.py: pipeline tests exercise
# correctness for a *single* generated set; coverage tests verify that the
# *corpus as a whole* satisfies statistical and structural requirements (e.g.
# every rule has both PASS and FAIL examples).  Separating the two makes it
# easy to run only the fast pipeline tests during development.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

# WHY: DATA_DIR is a Path relative to the project root (i.e. where pytest is
# invoked).  If the directory does not exist the needs_full_dataset marker
# skips the entire class, so no test will fail on a fresh checkout.
DATA_DIR = Path("data/synthetic")

needs_full_dataset = pytest.mark.skipif(
    not DATA_DIR.exists(),
    reason="Full synthetic dataset not generated",
)


@needs_full_dataset
class TestViolationMatrixCoverage:
    """Verify that every planning rule has both PASS and FAIL examples."""

    def test_all_rule_outcomes_present(self) -> None:
        """R001, R002, and R003 must each appear with PASS and FAIL verdicts.

        # WHY: A corpus where a rule only appears with one outcome cannot train
        # a balanced classifier.  This test catches scenarios where the verdict
        # generator is always compliant (or always non-compliant) for a rule.
        """
        verdicts: dict[str, set[str]] = {}
        for gt_path in DATA_DIR.rglob("ground_truth.json"):
            gt = json.loads(gt_path.read_text())
            for rv in gt.get("rule_verdicts", []):
                rid = rv["rule_id"]
                verdicts.setdefault(rid, set()).add(rv["outcome"])
        for rule_id in ["R001", "R002", "R003"]:
            assert rule_id in verdicts
            assert "PASS" in verdicts[rule_id]
            assert "FAIL" in verdicts[rule_id]


@needs_full_dataset
class TestEdgeCaseCoverage:
    """Verify that every edge-case strategy appears at least once in the corpus."""

    def test_all_strategies_present(self) -> None:
        """All five edge-case strategies must appear in the edgecase/ sub-corpus.

        # WHY: Each strategy exercises a different failure mode of the extraction
        # pipeline.  If a strategy is absent the model cannot learn to handle
        # that failure mode.  This test will catch regressions where the strategy
        # selector loses a variant.
        """
        strategies: set[str] = set()
        ec_dir = DATA_DIR / "edgecase"
        for gt_path in ec_dir.rglob("ground_truth.json"):
            gt = json.loads(gt_path.read_text())
            s = gt.get("edge_case_strategy")
            if s:
                strategies.add(s)
        expected = {
            "missing_evidence",
            "conflicting_values",
            "low_confidence_scan",
            "partial_documents",
            "ambiguous_units",
        }
        assert strategies == expected
