"""PDF rasterisation — render PDF bytes to numpy image arrays.

# DESIGN: Rasterisation is the entry point for the degradation pipeline: raw
# PDF bytes (as generated by reportlab) are converted to per-page uint8 RGB
# arrays, which are then passed through compose()-built pipelines.
#
# WHY multiple back-ends with fallback: the project targets Windows ARM64 and
# Linux x86_64 CI environments.  pymupdf (fitz) is the preferred back-end
# because it bundles its own MuPDF library and has no external binary
# dependencies.  pdf2image is a strong alternative on Linux but requires the
# poppler binaries, which may not be present.  The fallback implementation uses
# only Pillow + io (always available) and renders a blank page with the correct
# dimensions derived from the PDF MediaBox — sufficient for degradation testing
# because the pipeline still applies noise, rotation, and compression to the
# blank canvas.
#
# WHY back-end selection at call time (not import time): lazy import means that
# modules that only use bbox_adjust or compose do not pay the cost of importing
# large PDF libraries.  Errors surface only when rasterise_pdf() is actually
# called, which keeps unit tests for compose/bbox_adjust fast and dependency-free.
"""

from __future__ import annotations

import numpy as np

from planproof.datagen.degradation.transforms import ImageArray

# ---------------------------------------------------------------------------
# Public constants
# ---------------------------------------------------------------------------

# WHY: 300 DPI is the canonical resolution for PlanProof documents (also used
# in rendering/models.py as CANONICAL_DPI).  Callers may override for testing
# or to match a specific scanner profile.
DEFAULT_DPI: int = 300


# ---------------------------------------------------------------------------
# Internal back-end implementations
# ---------------------------------------------------------------------------


def _rasterise_with_pymupdf(pdf_bytes: bytes, dpi: int) -> list[ImageArray]:
    """Render all pages using pymupdf (fitz).

    # WHY preferred: pymupdf bundles its own MuPDF renderer and has no external
    # binary dependency, making it the most portable choice.  It also supports
    # ARM64 Windows natively from PyPI.

    Args:
        pdf_bytes: Raw PDF file contents.
        dpi:       Target render resolution.

    Returns:
        One uint8 RGB ImageArray per page.
    """
    import fitz  # type: ignore[import-untyped]  # pymupdf

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    zoom = dpi / 72.0  # PDF native unit is 1/72 inch
    mat = fitz.Matrix(zoom, zoom)

    pages: list[ImageArray] = []
    for page in doc:
        pix = page.get_pixmap(matrix=mat, colorspace=fitz.csRGB, alpha=False)
        # pix.samples is a bytes object; reshape into (H, W, 3).
        arr = np.frombuffer(pix.samples, dtype=np.uint8).reshape(
            pix.height, pix.width, 3
        )
        pages.append(arr.copy())  # copy to own the buffer

    doc.close()
    return pages


def _rasterise_with_pdf2image(pdf_bytes: bytes, dpi: int) -> list[ImageArray]:
    """Render all pages using pdf2image (requires poppler on PATH).

    # WHY fallback: pdf2image is commonly available on Linux CI images where
    # poppler-utils is installed, but is unreliable on Windows ARM64.

    Args:
        pdf_bytes: Raw PDF file contents.
        dpi:       Target render resolution.

    Returns:
        One uint8 RGB ImageArray per page.
    """
    from pdf2image import convert_from_bytes  # type: ignore[import-untyped]

    pil_images = convert_from_bytes(pdf_bytes, dpi=dpi, fmt="RGB")
    return [np.array(img, dtype=np.uint8) for img in pil_images]


def _parse_pdf_page_size(pdf_bytes: bytes) -> tuple[int, int]:
    """Extract the first page's MediaBox dimensions from raw PDF bytes.

    # DESIGN: A minimal regex-free parser that scans for the first /MediaBox
    # entry.  This avoids importing a full PDF parser just for the blank-page
    # fallback.  The function is intentionally lenient — if parsing fails it
    # returns a reasonable A4-at-300-DPI default.

    Returns:
        (width_px, height_px) at the caller's DPI.  The function returns pixel
        dimensions at 72 DPI (PDF native) which the caller scales.
    """
    # WHY: Search for the pattern "MediaBox [ x0 y0 x1 y1 ]" in the raw bytes.
    # PDF allows arbitrary whitespace so we scan character by character.
    text = pdf_bytes.decode("latin-1", errors="replace")
    import re

    match = re.search(
        r"/MediaBox\s*\[\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\]", text
    )
    if match:
        x0, y0, x1, y1 = (float(g) for g in match.groups())
        # Return width and height in PDF user units (1 unit = 1/72 inch).
        return int(round(x1 - x0)), int(round(y1 - y0))

    # WHY A4 default: most planning documents are A4 or A3; A4 is a safe
    # assumption for the blank-page fallback.
    return 595, 842  # A4 in PDF user units (points)


def _rasterise_fallback(pdf_bytes: bytes, dpi: int) -> list[ImageArray]:
    """Return one blank white page per PDF page at the correct DPI dimensions.

    # WHY: When neither pymupdf nor pdf2image is available we still need a valid
    # ImageArray to pass through the degradation pipeline.  A blank white page
    # is safe: noise, rotation, and JPEG transforms all produce non-trivial
    # output on a blank canvas, so the rest of the pipeline can be tested and
    # benchmarked even without a working PDF renderer.
    #
    # DESIGN: We attempt to count pages by scanning for the /Type /Page token
    # in the raw bytes.  If that fails we assume one page.  The MediaBox is
    # used to get correct dimensions; falling back to A4 if it cannot be parsed.

    Args:
        pdf_bytes: Raw PDF file contents (used only for size/page-count hints).
        dpi:       Target render resolution.

    Returns:
        A list of blank uint8 RGB ImageArrays, one per detected PDF page.
    """
    import re

    # Count /Type /Page tokens (each real page has one).
    text = pdf_bytes.decode("latin-1", errors="replace")
    page_count = max(1, len(re.findall(r"/Type\s*/Page\b", text)))

    # Derive pixel dimensions from MediaBox.
    pts_w, pts_h = _parse_pdf_page_size(pdf_bytes)
    scale = dpi / 72.0
    px_w = max(1, int(round(pts_w * scale)))
    px_h = max(1, int(round(pts_h * scale)))

    # WHY white (255): blank white simulates an unprinted scan bed, which is
    # the neutral baseline for all degradation transforms.
    blank: ImageArray = np.full((px_h, px_w, 3), fill_value=255, dtype=np.uint8)
    return [blank.copy() for _ in range(page_count)]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def rasterise_pdf(pdf_bytes: bytes, dpi: int = DEFAULT_DPI) -> list[ImageArray]:
    """Render each page of a PDF to a uint8 RGB numpy array.

    # DESIGN: Three back-ends are tried in preference order:
    #   1. pymupdf (fitz)   — preferred; no external binaries required.
    #   2. pdf2image         — requires poppler; good on Linux CI.
    #   3. blank-page fallback — always works; sufficient for pipeline testing.
    #
    # WHY try/except at import time (not at top-level): lazy imports keep the
    # module loadable in environments where neither optional library is installed.
    # The caller receives a valid list of ImageArrays regardless of which
    # back-end runs, so degradation pipeline code is decoupled from PDF rendering.

    Args:
        pdf_bytes: Raw PDF file bytes (e.g. from GeneratedDocument.content_bytes).
        dpi:       Render resolution in dots per inch.  Default is 300 DPI,
                   matching CANONICAL_DPI used throughout the PlanProof pipeline.

    Returns:
        A list of uint8 RGB ImageArrays, one element per page in the PDF.
        Each array has shape (H, W, 3) where H and W depend on the page size
        and the requested DPI.

    Raises:
        ValueError: If pdf_bytes is empty.
    """
    if not pdf_bytes:
        raise ValueError("pdf_bytes must not be empty")

    # WHY try each back-end in preference order rather than detecting at import
    # time: the user may install/uninstall optional dependencies between runs
    # and we want the best available renderer without requiring a restart.

    # Back-end 1: pymupdf
    try:
        return _rasterise_with_pymupdf(pdf_bytes, dpi)
    except ImportError:
        pass  # pymupdf not installed — try next back-end
    except Exception as exc:  # noqa: BLE001
        # WHY catch-all: a corrupted PDF or an unexpected pymupdf error must
        # not crash the entire data-generation pipeline.  Log and fall through.
        import warnings

        warnings.warn(
            f"pymupdf failed to rasterise PDF ({exc!r}); trying pdf2image.",
            stacklevel=2,
        )

    # Back-end 2: pdf2image
    try:
        return _rasterise_with_pdf2image(pdf_bytes, dpi)
    except ImportError:
        pass  # pdf2image not installed — use blank-page fallback
    except Exception as exc:  # noqa: BLE001
        import warnings

        warnings.warn(
            f"pdf2image failed to rasterise PDF ({exc!r}); using blank-page fallback.",
            stacklevel=2,
        )

    # Back-end 3: blank-page fallback — always succeeds
    return _rasterise_fallback(pdf_bytes, dpi)
